name: Auto-Clean

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    inputs:
      NUMBER:
        default: '5'
        required: false
        type: string

permissions: write-all

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  auto_clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: ${{inputs.NUMBER || '5'}}
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
